### ISSUE TITLE
The coffeescript compiler at 'coffee' is currently unavailable

### ISSUE THREAD

**Issue by xaviershay** [Sutto/barista#12]
Upgraded to 0.6.0, get the following error in my server log, and no compilation:
The coffeescript compiler at 'coffee' is currently unavailable

It is available:
    $ which coffee
    /usr/local/bin/coffee

the preamble branch on my fork works for me. Won't get a chance to investigate until next week.

**Comment by stephencelis** [comment]
Same here.

**Comment by Sutto** [comment]
Odd - not sure what's going on here. Will take a look very shortly.

**Comment by nicolasblanco** [comment]
I also had this problem. I installed Node+NPM via the official method in HOME (without sudo) :
https://gist.github.com/579814
and installed coffee-script via npm. and even if 'coffee' was in the PATH, Barista did not detect it.

I think that's because of the way barista detects coffee :
https://github.com/Sutto/barista/blob/master/lib/barista/compilers/node.rb#L8 :

using test -x will only return true if an absolute path to a file is given.

For example, testing on 'ls' returns false :

<pre>
irb(main):001:0> system("test -x 'ls' >/dev/null 2>&1")
false

irb(main):003:0> system("test -x '/bin/ls' >/dev/null 2>&1")
true
</pre>


So maybe you'll have to change this.
The workaround is to configure the full path in the configuration.
As I installed coffee via NPM in ~/local I added :

<pre>
Barista.configure do |c|
  #...
  c.bin_path = File.expand_path("~/local/bin/coffee")
  # ...
end
</pre>

**Comment by Sutto** [comment]
Oh wow, that's my mistake. Thanks for picking up that glaring oversight.

As a side note, I'm currently porting it across to use the Ruby coffee-script gem to avoid these issues / move that part of barista and that'll be done in the next 2-3 days

**Comment by Sutto** [comment]
I've just pushed 0.6.1 with a hopeful fix for this issue - can you guys take a look and confirm if it fixes it for you?

Re. the native version, slainer68's done a bunch of work and I'll be finishing up my work tomorrow as well so 0.7.0 isn't far off (since it introduces deprecated options).

Cheers

**Comment by xaviershay** [comment]
0.6.1 fixes for me, thanks
