### ISSUE TITLE
Integrate Haml Filter support?

### ISSUE THREAD

**Issue by perezd** [Sutto/barista#3]
It'd be pretty cool if all I had to do was install barista to get full on coffeescript support for my entire codebase, don't really like having to install an old plugin for that. Any chance you'd port it over to your gem?

**Comment by perezd** [comment]
Oh, I see they've updated it since your original blog post. however, any chance on just including it as a dependency? that way we get it for free!

**Comment by Sutto** [comment]
I'm very interested in doing this - I'll whip up a prototype shortly (I'll integrate it directly into barista so it uses the same compiler / error reporting) - Cheers for the idea.

**Comment by Sutto** [comment]
Since it's been a while since I've updated it, I just thought I'd give a quick preview of what's coming in 1.0 / the next couple of releases for Barista: http://puu.sh/sNY

It'll automatically use raw coffeescript if you're in development (unless you tell it not to), otherwise it'll convert and embed the converted js.

**Comment by Sutto** [comment]
Please check out master / the current gem version (0.7.0.pre2) - If haml is detected, it'll automatically set up a filter for you.

Cheers

**Comment by perezd** [comment]
Thats fantastic! Thanks!!!
